name: E2E-testing
on: [push]
jobs:
  e2e:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: hyperse-main
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres@localhost:5432/hyperse-main
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          # cache: 'pnpm' # You can active this cache when your repo has a lockfile

      - name: Install deps (with cache)
        run: yarn install

      - name: Install playwright
        run: yarn playwright install chromium

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.name }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      - name: Setup Prisma
        run: yarn prebuild

      - name: Build and test
        run: yarn build && yarn test-start && yarn test-dev
        env:
          PORT: 3000
          NODE_ENV: test
          DATABASE_URL: postgres://postgres@localhost:5432/hyperse-main
          LUCIA_AUTH_URL: https://www.hyperse.net
          LUCIA_AUTH_SECRET: hyperse-main
          GITHUB_CLIENT_ID: 93134c1def770bc34d5a
          GITHUB_CLIENT_SECRET: 62820d036d828cabef98d70d3e5137afa303cbe0
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            playwright/test-results
